# ================= APP =================
spring.application.name=complaint-simple
server.port=8080

# ================= DATABASE =================
# Yaha apna MySQL username/password daalna - database khud ban jayega
spring.datasource.url=jdbc:mysql://localhost:3306/complaint_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=yashika
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================= JPA / HIBERNATE =================
# update = tables khud create/update ho jayenge entity classes se
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ================= THYMELEAF =================
# false rakho development mein taaki HTML changes turant dikhein bina restart ke
spring.thymeleaf.cache=false
